### ISSUE TITLE
CTRE_Phoenix Tools.lvlib is missing from the repository.

### ISSUE THREAD

**Issue by mballawickersigpi** [CrossTheRoadElec/Phoenix6-LabVIEW#1]
The CTRE_Phoenix Tools\CTRE_Phoenix Tools.lvlib is missing.
All the vis are dependent on this lvlib so they all come up broken.

![image](https://user-images.githubusercontent.com/111312905/213843037-824fad1d-6836-44a3-830a-1988a80cde62.png)

**Comment by ozrien** [comment]
Was the normal Phoenix LabVIEW PC install done via the **Phoenix Framework Installer**?
https://store.ctr-electronics.com/software/

Phoenix Pro LabVIEW has the same dependencies as Phoenix 5 LabVIEW.

You may also have to deploy the LabVIEW files to the roboRIO (just like Phoenix 5).
This can be done with Tuner v1 or Tuner X
Tuner v1: https://v5.docs.ctr-electronics.com/en/stable/ch06_PrepRobot.html?highlight=labview#labview
Tuner X has the same buttons under Settings menu.

**Comment by CoryNessCTR** [comment]
There was a missing file in the repo, I added it in just now, and updated the readme instructions, as you also need to rename the directory once it makes it to the user.lib directory.

Let us know if there's any other issues you run into!
